version: "1.1"

services:
  db:
    image: postgres:14
    container_name: vehicle-db
    restart: always
    environment:
      POSTGRES_DB: vehicle-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '45432:5432'
    networks:
      - appnet
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: vehicle-management:latest
    container_name: vehicle-backend
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL:-jdbc:postgresql://db:5432/vehicle-db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-password}
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - appnet
  
  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
      args:
        NGINX_CONF: ${NGINX_CONF:-nginx.conf}
    container_name: vehicle-portal
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - appnet
    
volumes:
  db-data:
    driver: local
    
networks:
  appnet:
    driver: bridge