version: "1.0"

services:
  db:
    image: postgres:14
    container_name: vehicle_db
    environment:
      POSTGRES_DB: vehicle_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '45432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vehicle-management:latest
    container_name: vehicle-app
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/vehicle_db
      DB_USER: postgres
      DB_PASS: password
    ports:
      - "8088:8088"

volumes:
  db-data:
    driver: local