version: "1.1"

services:
  db:
    image: postgres:14
    container_name: vehicle_db
    environment:
      POSTGRES_DB: vehicle_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '45432:5432'
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: vehicle-management:latest
    container_name: vehicle-backend
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/vehicle_db
      DB_USER: postgres
      DB_PASS: password
    ports:
      - "8088:8088"
    restart: unless-stopped
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vehicle-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    
volumes:
  db-data:
    driver: local