server:
  port: 8088
spring:
  application:
    name: Vehicle Management
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vehicle_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  file:
    name: logs/app.log
  level:
    root: INFO