CREATE TABLE IF NOT EXISTS vehicle (
    vehicle_id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    type                  VARCHAR(50),
    use_of_vehicle        VARCHAR(30),
    derivative            VARCHAR(100),
    year                  INTEGER NOT NULL,
    price                 NUMERIC(12,2) NOT NULL CHECK (price >= 0),
    registration_date     DATE,
    kilometers            INTEGER,
    description           VARCHAR(4000),
    eco_label             VARCHAR(1),
    number_of_doors       INTEGER,
    transmission_type     VARCHAR(30),
    fuel_icon             VARCHAR(30),
    visit_counter         INTEGER,
    dealer_link           VARCHAR(500),
    supplier_website_url  VARCHAR(500),
    supplier_internal_code VARCHAR(50),

    created_by            VARCHAR(100) NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_by            VARCHAR(100),
    updated_at            TIMESTAMP WITH TIME ZONE,
    is_active             BOOLEAN NOT NULL DEFAULT TRUE
);