# auth
POST http://localhost:8088/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

###

GET http://localhost:4566/test-bucket/
Authorization: AWS4-HMAC-SHA256 Credential=test-access-key/test_secret