server:
  port: 8088
spring:
  application:
    name: Vehicle Management
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vehicle-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
info:
  build:
    time: "@buildTime@"
management:
  endpoints:
    web:
      exposure:
        include: info
  endpoint:
    info:
      access: read_only
logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
    org.springframework.security: DEBUG