server:
  port: 8080
spring:
  application:
    name: Vehicle Management
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/vehicle-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
info:
  build:
    time: "@buildTime@"
management:
  endpoints:
    web:
      exposure:
        include: info
  endpoint:
    info:
      access: read_only
jwt:
  secret: Zm9vYmFyYmF6cXV4MTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
swagger:
  server:
    url: https://vehicle-management.fly.dev
logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
    org.springframework.security: DEBUG

# AWS S3 Configuration
cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
      max-file-size: ${AWS_S3_MAX_FILE_SIZE:5242880}
      endpoint: ${AWS_S3_ENDPOINT}
    region:
      static: ${AWS_REGION:us-east-1}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}